### ISSUE TITLE
Text relocations crash using Marshmallow

### ISSUE THREAD

**Issue by aaronennis5778** [dm77/barcodescanner#170]
Using both the zxing and zbar libraries, there are crashes related to text relocations using Marshmallow.

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.harristeeter.htmobile-1/lib/arm/libiconv.so: has text relocations
                                         at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                         at java.lang.System.loadLibrary(System.java:1076)
                                         at me.dm7.barcodescanner.zbar.ZBarScannerView.<clinit>(ZBarScannerView.java:32)
                                         at com.harristeeter.htmobile.activities.SimpleScannerActivity.onCreate(SimpleScannerActivity.java:19)
                                         at android.app.Activity.performCreate(Activity.java:6251)
                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by chrisfoulds** [comment]
Also getting this, can new libs be made ?

**Comment by rajeefmk** [comment]
@aaronennis5778 @chrisfoulds This issue has been fixed from 1.8.3 and above (Ref: https://github.com/dm77/barcodescanner/issues/123 )

**Comment by dm77** [comment]
What @rajeefmk  said. Thank you guys

**Comment by sethwhite2** [comment]
@dm77 @rajeefmk  this issue is not resolved.

I'm using 1.9 and I'm experiencing the same issue.

**Comment by sethwhite2** [comment]
I'm able to resolve this issue by adding this to my project's build.gradle file:

```
android {
    ...
    sourceSets {
        main.jniLibs.srcDirs = ['libs']
        test.jniLibs.srcDirs = ['libs']
    }
}
```
